"""Shared Protocol interfaces for all MCP server adapters.

Every agent and skill that calls an MCP server accepts one of these
Protocols as a parameter. Concrete adapter classes wrap the actual
mcp_servers.* modules and satisfy these interfaces.

One adapter = a hypothetical seam.
Two adapters (real + test stub) = a real seam that earns its keep.
"""
from __future__ import annotations

from typing import Any, Protocol


class GcpResourceClient(Protocol):
    """Interface over gcp-resource-mcp: VM, bucket, and VPC tools."""

    def get_vm_status(self, project_id: str, zone: str, instance_name: str) -> dict[str, Any]: ...
    def get_bucket_status(self, project_id: str, bucket_name: str) -> dict[str, Any]: ...
    def get_vpc_status(self, project_id: str, network_name: str) -> dict[str, Any]: ...
    def list_project_resources(self, project_id: str, resource_type: str) -> list[dict[str, Any]]: ...
    def create_vm(self, project_id: str, zone: str, instance_name: str, **kwargs: Any) -> dict[str, Any]: ...
    def delete_vm(self, project_id: str, zone: str, instance_name: str) -> dict[str, Any]: ...
    def create_bucket(self, project_id: str, bucket_name: str, region: str, **kwargs: Any) -> dict[str, Any]: ...
    def delete_bucket(self, project_id: str, bucket_name: str) -> dict[str, Any]: ...
    def create_vpc_network(self, project_id: str, network_name: str, **kwargs: Any) -> dict[str, Any]: ...
    def delete_vpc_network(self, project_id: str, network_name: str) -> dict[str, Any]: ...


class PostgresClient(Protocol):
    """Interface over postgres-mcp: all database operations."""

    async def get_provisioning_job(self, job_id: str) -> dict: ...
    async def get_provisioning_job_by_idempotency_key(self, idempotency_key: str) -> dict: ...
    async def create_provisioning_job(self, job_data: dict) -> dict: ...
    async def update_job_status(self, job_id: str, status: str) -> dict: ...
    async def cancel_job(self, job_id: str) -> dict: ...
    async def get_infra_request(self, infra_request_id: str) -> dict: ...
    async def create_infra_request(self, request_data: dict) -> dict: ...
    async def update_request_status(
        self, infra_request_id: str, status: str, confirmed_at: str | None
    ) -> dict: ...
    async def get_user_role(self, user_id: str) -> dict: ...
    async def verify_api_key(self, api_key: str) -> dict: ...
    async def get_daily_usage_count(self, user_id: str) -> dict: ...
    async def increment_daily_usage(self, requesting_user: str, daily_limit: int) -> dict: ...
    async def create_audit_event(self, event_data: dict) -> dict: ...


class PubSubClient(Protocol):
    """Interface over pubsub-mcp: event publishing."""

    async def publish_provisioning_request(self, event: dict) -> dict: ...
    async def publish_status_event(self, event: dict) -> dict: ...
    async def publish_audit_event(self, event: dict) -> dict: ...
